#!/bin/sh

./01_downloadNewBillFiles $*

count=`cat .count`

if [ "$count" != "0" ]; then

    ./02_importBills $*

    ./03_importVersions $*

    ./04_connectSections $*

    ./05_updateStatusDate $*

    ./06_thisBillWoulds $*
fi

/bin/rm -f .count

./99_testData $*

