#!/bin/sh

if [ "$1" != "-x" ]; then
    ./01_downloadNewBillFiles $*
fi

./02_removeExtras $*

./03_importBills $*

./04_importVersions $*

./05_connectSections $*

./07_updateStatusDate $*

./07_thisBillWoulds $*

./99_testData $*

