#!/usr/bin/perl

require "cmds.pl";

%options = &readOptions;

$session = $options{"session"};

for ($idx = 0; $idx < scalar(@ARGV); $idx++) {
    if ($ARGV[$idx] eq "-s") { $session = $ARGV[$idx+1]; }
    if ($ARGV[$idx] eq "-v") { $verbose = 1; }
    if ($ARGV[$idx] eq "-q") { $quiet = 1; }
}

$done = "n";

while ($done ne "y") {

    $cmd = "find leginfo.public.ca.gov/pub/".$session."/bill -name \*status.html | sort";
    @statuses = `$cmd`;
    chomp(@statuses);

    $done = "y";

    $deleted = 0;

    undef %status;

    foreach (@statuses) {
        $statusFile = $_;

        @p = split '/', $statusFile;
        $fileName = pop @p;
        @p = split '_', $fileName;
        $billNum = $p[0]."_".$p[1];
        # print "statusFile \"".$statusFile."\" -> \"".$billNum."\"\n";

        $idx = 0;
        while (defined($status{$billNum}[$idx])) { $idx++; }

        $status{$billNum}[$idx] = $statusFile;
    }

    foreach (sort keys %status) {
        $billNum = $_;
        $idx = 0;
        while (defined($status{$billNum}[$idx])) {
            #print "status{".$billNum."}[".$idx."] = \"".$status{$billNum}[$idx]."\"\n";
            $idx++;
        }

        if (defined($status{$billNum}[1])) {
            # print "deleting status{".$billNum."}[0] = \"".$status{$billNum}[0]."\"\n";
            unlink ($status{$billNum}[0]);
            $deleted++;
            $done = "n";
        }
    }

    print "deleted status file # ".$deleted." ";
    if ($done eq "y") { print "Done."; } else { print "Not Done."; }
    print "\n";
}

$done = "n";

while ($done ne "y") {

    $cmd = "find leginfo.public.ca.gov/pub/".$session."/bill -name \*history.html | sort";
    @historys = `$cmd`;
    chomp(@historys);

    $done = "y";

    $deleted = 0;

    undef %history;

    foreach (@historys) {
        $historyFile = $_;

        @p = split '/', $historyFile;
        $fileName = pop @p;
        @p = split '_', $fileName;
        $billNum = $p[0]."_".$p[1];
        # print "historyFile \"".$historyFile."\" -> \"".$billNum."\"\n";

        $idx = 0;
        while (defined($history{$billNum}[$idx])) { $idx++; }

        $history{$billNum}[$idx] = $historyFile;
    }

    foreach (sort keys %history) {
        $billNum = $_;
        $idx = 0;
        while (defined($history{$billNum}[$idx])) {
            #print "history{".$billNum."}[".$idx."] = \"".$history{$billNum}[$idx]."\"\n";
            $idx++;
        }

        if (defined($history{$billNum}[1])) {
            # print "deleting history{".$billNum."}[0] = \"".$history{$billNum}[0]."\"\n";
            unlink ($history{$billNum}[0]);
            $deleted++;
            $done = "n";
        }
    }

    print "deleted history file # ".$deleted." ";
    if ($done eq "y") { print "Done."; } else { print "Not Done."; }
    print "\n";
}

print "\n";

exit(0);
