#!/usr/bin/perl

require "cmds.pl";

%options = &readOptions;

$session = $options{"session"};

for ($idx = 0; $idx < scalar(@ARGV); $idx++) {
    if ($ARGV[$idx] eq "-s") { $session = $ARGV[$idx+1]; }
    if ($ARGV[$idx] eq "-v") { $verbose = 1; }
}

%month = ( "JANUARY" => 1, "FEBRUARY" => 2, "MARCH" => 3, "APRIL" => 4, "MAY" => 5, "JUNE" => 6,
           "JULY" => 7, "AUGUST" => 8, "SEPTEMBER" => 9, "OCTOBER" => 10, "NOVEMBER" => 11, "DECEMBER" => 12 );

@billInfos = &doSqlResults("select pk, bill_num from bills where session_yrs = '".$session."';");
chomp(@billInfos);

foreach (@billInfos) {
    ($pk, $billNum) = split '\t', $_;
    $billInfo{$billNum} = $pk;
}

$cmd = "find leginfo.public.ca.gov/pub/".$session."/bill -name \*_bill_\* | grep -v status | grep -v history\n";

if (defined($verbose)) { print $cmd; }

@versionsInFiles = &doCmdResults($cmd);

$sql = "select v1.file from bill_versions v1, bills b1 where b1.session_yrs = '".$session."' and b1.pk = v1.bill_pk;";

if (defined($verbose)) { print $sql."\n"; }

@versionsInDB = &doSqlResults($sql);

print "\nFound bill versions in files # ".scalar(@versionsInFiles)." and bill versions in DB # ".scalar(@versionsInDB)."\n";

if (scalar(@versionsInFiles) > scalar(@versionsInDB)) {

    $maxPk = &doSqlResult("select max(pk) from bill_versions;");

    if ($maxPk eq "NULL") { $maxPk = 0; }

    foreach (@versionsInDB) { $versionsInDB{$_} = 1; }

    $idx = 0;

    foreach (@versionsInFiles) {

        $file = $_;

        $file =~ s/^leginfo.public.ca.gov\/pub\///;

        # if (defined($verbose)) { print "\nNOT YET, file: \"".$file."\"\n"; }

        if ( ! defined($versionsInDB{$file})) {

            if (defined($verbose)) { print "\nIN CHECK, file: \"".$file."\"\n"; }

            @parts = split '_', $file;

            splice @parts, 0, 5;

            $versionType = join "_", @parts;
            $versionType =~ s/\.html$//;

            @parts = split '/', $file;
            $last = pop @parts;
            ($house, $num, $x) = split '_', $last;

            $billNum = $house."_".$num;

            if (!defined($billInfo{$billNum})) {
                print "ERROR with billNum: ".$billNum."\n";
            } else {

                $billPk = $billInfo{$billNum};

                $cmd = "/usr/bin/tidy -bare -wrap 0 leginfo.public.ca.gov/pub/".$file." 2>/dev/null\n";
                @lines = `$cmd`;
                chomp(@lines);

                foreach (@lines) {
                    $line = $_;

                    if ($line =~ /<meta name=\"FILEDATE\" content=\"([0-9]{8})\">/) { $dateStr = substr($1,0,4)."-".substr($1,4,2)."-".substr($1,6,2); }
                    if ($line =~ /<meta name=\"TOPIC\" content=\"(.*)\">/) { $topic = $1; }
                    if ($line =~ /<meta name=\"AUTHOR\" content=\"(.*)\">/) { $authors = $1; }
                    if ($line =~ /<meta name=\"COAUTHOR\" content=\"(.*)\">/) { $coauthors = $1; }
                }

                undef $title;

                foreach (@lines) {
                    $line = $_;
                    if ($line =~ /LEGISLATIVE COUNSEL'S DIGEST/) { $in = "no"; }
                    if ($in eq "yes") { $line =~ s/^\s*//; $line =~ s/\s*$//; $title .= " ".$line; }
                    if ($line =~ /^\s\s*([A-Z][A-Z]*) [0-9][0-9]*, [0-9]{4}\s*$/) { if (defined($month{$1})) { $in = "yes"; } }
                }

                $maxPk++;

                $topic =~ s/'/''/g; $topic =~ s/^\s*//; $topic =~ s/\s*$//;
                $title =~ s/'/''/g; $title =~ s/^\s*//; $title =~ s/\s*$//;
                $authors =~ s/'/''/g; $authors =~ s/^\s*//; $authors =~ s/\s*$//;
                $coauthors =~ s/'/''/g; $coauthors =~ s/^\s*//; $coauthors =~ s/\s*$//;

                if (defined($verbose)) {
                    print "\n";
                    print "    file: \"".$file."\"\n";
                    print "    dateStr: \"".$dateStr."\"\n";
                    print "    versionType: \"".$versionType."\"\n";
                    print "    lines # ".scalar(@lines)."\n";
                    print "    topic: \"".$topic."\"\n";
                    print "    title: \"".$title."\"\n";
                    print "    authors: \"".$authors."\"\n";
                    print "    coauthors: \"".$coauthors."\"\n";
                }

                push @sql, "insert into bill_versions (pk, bill_pk, file, file_date, kind, topic, title, authors, coauthors) ". 
                           "values (".$maxPk.", ".$billPk.", '".$file."', '".$dateStr."', '".$versionType."', ".
                                  "'".$topic."', '".$title."', '".$authors."', '".$coauthors."');\n";
            }
        }
    }
}

open M, "| ".&mysql; foreach (@sql) { print M $_; } close M;

print "\nBill versions added # ".scalar(@sql)."\n";

@sql = ();

print "\n";

exit(0);
